services:
  node_api:
    build: .
    container_name: node_api
    restart: unless-stopped
    expose:
      - "3000" # Porta HTTP interna
      - "3001" # Porta HTTPS interna
    volumes:
      - ./app:/app
      - /app/node_modules
    networks:
      - jedieduca-network

networks:
  jedieduca-network:
    external: true